# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journey',
            name='members',
            field=models.ManyToManyField(through='journeys.JourneyMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
